@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jun 13 00:05:35 +0800 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_test_pattern_gen_behav -key {Behavioral:sim_1:Functional:tb_test_pattern_gen} -tclbatch tb_test_pattern_gen.tcl -view H:/git_respo/10_4fps_1ch_148_5ddr/FPGA_TEST_PATTERN_10_4fps_4ch_freq1/1in4lane_freq0_297_37125_behav.wcfg -log simulate.log"
call xsim  tb_test_pattern_gen_behav -key {Behavioral:sim_1:Functional:tb_test_pattern_gen} -tclbatch tb_test_pattern_gen.tcl -view H:/git_respo/10_4fps_1ch_148_5ddr/FPGA_TEST_PATTERN_10_4fps_4ch_freq1/1in4lane_freq0_297_37125_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
