@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed May 18 19:41:08 +0800 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_test_pattern_gen_behav -key {Behavioral:sim_1:Functional:tb_test_pattern_gen} -tclbatch tb_test_pattern_gen.tcl -view C:/Users/Administrator/Desktop/IMX305/FPGA_TEST_PATTERN/tb_par_sensor_word_gen_behav.wcfg -log simulate.log"
call xsim  tb_test_pattern_gen_behav -key {Behavioral:sim_1:Functional:tb_test_pattern_gen} -tclbatch tb_test_pattern_gen.tcl -view C:/Users/Administrator/Desktop/IMX305/FPGA_TEST_PATTERN/tb_par_sensor_word_gen_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
